In [ ]:
#List and its operations.
#List is similar to Vector but it can contain diffrent datatypes.

list1<-list("Suraj",23,50+2i,40L)
list1
typeof(list1)
class(list1)

[[1]]
[1] "Suraj"

[[2]]
[1] 23

[[3]]
[1] 50+2i

[[4]]
[1] 40

[1] "list"

[1] "list"

In [ ]:
vec<-c(1,2,15)
vec_char<-c("Suraj","Kumar","Gupta")
vec_log<-c(TRUE,FALSE,FALSE,TRUE)
typeof(vec)
typeof(vec_char)
typeof(vec_log)
class(vec)
class(vec_char)
class(vec_log)
print("")
list2<-list(vec,vec_char,vec_log)
typeof(list2)
class(list2)

[1] "double"

[1] "character"

[1] "logical"

[1] "numeric"

[1] "character"

[1] "logical"

[1] ""

[1] "list"

[1] "list"

In [ ]:
#print using index

list2
list2[1]
list2[2]
list2[3]

[[1]]
[1]  1  2 15

[[2]]
[1] "Suraj" "Kumar" "Gupta"

[[3]]
[1]  TRUE FALSE FALSE  TRUE

[[1]]
[1]  1  2 15

[[1]]
[1] "Suraj" "Kumar" "Gupta"

[[1]]
[1]  TRUE FALSE FALSE  TRUE

In [8]:
#list in list

list3<-list(c("Suraj","Sahil","Ajay"),matrix(c(20,21,23),nrow = 1),list("DS","C++","C#"))
list3
print("")

#Named the columns
names(list3)<-c("StudentName","Age","Subjects")
list3

#Can Search with name
print("")
list3["Age"]

[[1]]
[1] "Suraj" "Sahil" "Ajay"

[[2]]
     [,1] [,2] [,3]
[1,]   20   21   23

[[3]]
[[3]][[1]]
[1] "DS"

[[3]][[2]]
[1] "C++"

[[3]][[3]]
[1] "C#"

[1] ""

$StudentName
[1] "Suraj" "Sahil" "Ajay"

$Age
     [,1] [,2] [,3]
[1,]   20   21   23

$Subjects
$Subjects[[1]]
[1] "DS"

$Subjects[[2]]
[1] "C++"

$Subjects[[3]]
[1] "C#"

[1] ""

$Age
     [,1] [,2] [,3]
[1,]   20   21   23

In [10]:
#Unlist a list and it will act as vector
x<-unlist(list3)
x

StudentName1 StudentName2 StudentName3         Age1         Age2         Age3
     "Suraj"      "Sahil"       "Ajay"         "20"         "21"         "23"
   Subjects1    Subjects2    Subjects3
        "DS"        "C++"         "C#"

In [12]:
#Merge List
a<-list(1,2,32)
b<-list(4,71,90)
mergeList<-list(a,b)
mergeList

[[1]]
[[1]][[1]]
[1] 1

[[1]][[2]]
[1] 2

[[1]][[3]]
[1] 32


[[2]]
[[2]][[1]]
[1] 4

[[2]][[2]]
[1] 71

[[2]][[3]]
[1] 90

In [13]:
#manipulate list
list3[1]<-"Std"
list3

$StudentName
[1] "Std"

$Age
     [,1] [,2] [,3]
[1,]   20   21   23

$Subjects
$Subjects[[1]]
[1] "DS"

$Subjects[[2]]
[1] "C++"

$Subjects[[3]]
[1] "C#"

In [14]:
#Can drop a data from list
list3[1]<-NULL
list3

$Age
     [,1] [,2] [,3]
[1,]   20   21   23

$Subjects
$Subjects[[1]]
[1] "DS"

$Subjects[[2]]
[1] "C++"

$Subjects[[3]]
[1] "C#"